In [75]:
import pandas as pd
import numpy as np

## Data Preprocessing
* add a result column (done)
* drop the time, full_time_goals column (done)
* fill in the null values in the dataset as averages (done)

### Data Exploration

In [76]:
dataset = pd.read_csv("train.csv", index_col=0)

In [77]:
dataset.shape

(39992, 24)

In [78]:
dataset.tail(5)

,Division,Time,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,...,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef
39995,15,NaN,231.0,309.0,0.0,1.0,0.0,0.0,-1,4.0,...,17.0,3.0,3.0,3.0,1.0,0.0,0.0,2.102645,3.404282,4.155226
39996,15,NaN,248.0,398.0,4.0,0.0,2.0,0.0,-1,15.0,...,8.0,8.0,4.0,1.0,2.0,0.0,0.0,1.340170,5.956310,10.423542
39997,15,NaN,453.0,126.0,1.0,2.0,1.0,1.0,-1,15.0,...,7.0,6.0,5.0,2.0,0.0,0.0,0.0,1.963689,3.506588,4.638715
39998,13,NaN,164.0,403.0,2.0,2.0,1.0,2.0,-1,11.0,...,22.0,5.0,7.0,0.0,0.0,0.0,0.0,4.050577,3.852988,1.985771
39999,6,NaN,271.0,269.0,1.0,1.0,0.0,0.0,-1,5.0,...,12.0,2.0,2.0,2.0,3.0,0.0,0.0,1.732761,3.924194,5.616183

In [79]:
dataset.head(5)

,Division,Time,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,...,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef
0,0,NaN,152.0,426.0,0.0,0.0,0.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.627690,3.577721,2.198600
1,0,NaN,216.0,341.0,2.0,2.0,0.0,1.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.608321,4.251999,6.533805
2,0,NaN,223.0,119.0,2.0,2.0,2.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.166811,3.486596,3.821467
3,0,NaN,68.0,137.0,2.0,1.0,0.0,1.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.259244,3.592401,3.460103
4,1,NaN,425.0,225.0,2.0,2.0,1.0,0.0,-1,13.0,...,15.0,4.0,10.0,3.0,4.0,1.0,0.0,2.424278,3.414191,3.282876

In [81]:
dataset.isnull().sum()

Division                    0
Time                    39992
home_team                   0
away_team                   0
full_time_home_goals        0
full_time_away_goals        0
half_time_home_goals        0
half_time_away_goals        0
Referee                     0
home_shots              15594
away_shots              15594
home_shots_on_target    15594
away_shots_on_target    15594
home_fouls              16344
away_fouls              16344
home_corners            15594
away_corners            15594
home_yellow_cards       15595
away_yellow_cards       15594
home_red_cards          15594
away_red_cards          15594
home_coef                   0
draw_coef                   0
away_coef                   0
dtype: int64

In [82]:
dataset[dataset["home_team"] == 271]

,Division,Time,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,...,away_fouls,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef
80,6,NaN,271.0,215.0,1.0,0.0,1.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.826184,3.280393,2.846371
355,6,NaN,271.0,117.0,1.0,1.0,1.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.408622,3.255997,2.441998
576,6,NaN,271.0,221.0,2.0,4.0,0.0,1.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.442480,3.175224,3.500889
957,6,NaN,271.0,292.0,2.0,0.0,1.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.508356,3.201723,3.344475
1278,6,NaN,271.0,304.0,2.0,1.0,1.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.638573,3.247475,3.095249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38694,6,NaN,271.0,198.0,2.0,1.0,1.0,1.0,-1,13.0,...,13.0,11.0,4.0,2.0,2.0,0.0,0.0,3.073592,3.307674,2.615607
39089,6,NaN,271.0,18.0,2.0,1.0,0.0,1.0,-1,15.0,...,19.0,8.0,11.0,1.0,5.0,0.0,0.0,2.462193,3.195825,3.437020
39209,6,NaN,271.0,460.0,0.0,0.0,0.0,0.0,-1,12.0,...,22.0,9.0,2.0,2.0,4.0,1.0,0.0,2.832181,3.524944,2.679365
39591,6,NaN,271.0,336.0,0.0,1.0,0.0,0.0,-1,11.0,...,13.0,2.0,2.0,6.0,3.0,1.0,0.0,2.721175,3.112784,3.112784
39999,6,NaN,271.0,269.0,1.0,1.0,0.0,0.0,-1,5.0,...,12.0,2.0,2.0,2.0,3.0,0.0,0.0,1.732761,3.924194,5.616183

### Data Cleansing

#### Add "result" column

In [83]:
result = [1 if x > y else -1 if x < y else 0 for x, y in zip(dataset["full_time_home_goals"], dataset["full_time_away_goals"])]

In [84]:
dataset["result"] = result

In [85]:
dataset.head()

,Division,Time,home_team,away_team,full_time_home_goals,full_time_away_goals,half_time_home_goals,half_time_away_goals,Referee,home_shots,...,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef,result
0,0,NaN,152.0,426.0,0.0,0.0,0.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.627690,3.577721,2.198600,0
1,0,NaN,216.0,341.0,2.0,2.0,0.0,1.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.608321,4.251999,6.533805,0
2,0,NaN,223.0,119.0,2.0,2.0,2.0,0.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.166811,3.486596,3.821467,0
3,0,NaN,68.0,137.0,2.0,1.0,0.0,1.0,-1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.259244,3.592401,3.460103,1
4,1,NaN,425.0,225.0,2.0,2.0,1.0,0.0,-1,13.0,...,4.0,10.0,3.0,4.0,1.0,0.0,2.424278,3.414191,3.282876,0

In [86]:
dataset["Referee"].unique()

array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
       116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
       129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158], dtype=int64)

Drop unecessary columns

In [87]:
dataset = dataset.drop(columns=["Time", "full_time_home_goals", "full_time_away_goals"])

In [88]:
dataset.head()

,Division,home_team,away_team,half_time_home_goals,half_time_away_goals,Referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,...,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef,result
0,0,152.0,426.0,0.0,0.0,-1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.627690,3.577721,2.198600,0
1,0,216.0,341.0,0.0,1.0,-1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.608321,4.251999,6.533805,0
2,0,223.0,119.0,2.0,0.0,-1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.166811,3.486596,3.821467,0
3,0,68.0,137.0,0.0,1.0,-1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.259244,3.592401,3.460103,1
4,1,425.0,225.0,1.0,0.0,-1,13.0,11.0,5.0,7.0,...,4.0,10.0,3.0,4.0,1.0,0.0,2.424278,3.414191,3.282876,0

#### Fill in null values with averages

In [89]:
cols = ["home_shots", "away_shots", 'home_shots_on_target',
       'away_shots_on_target', 'home_fouls', 'away_fouls', 'home_corners',
       'away_corners', 'home_yellow_cards', 'away_yellow_cards',
       'home_red_cards', 'away_red_cards']
home_teams = dataset["home_team"].unique()
away_teams = dataset["away_team"].unique()

for home_team, away_team in zip(home_teams, away_teams):
    home_team_matches = dataset[dataset["home_team"] == home_team]
    away_team_matches = dataset[dataset["away_team"] == away_team]
    
    for idx in range(0, len(cols), 2):
        home_col = cols[idx]
        away_col = cols[idx + 1]
        home_col_new_value = home_team_matches[home_col].notnull().mean()
        away_col_new_value = away_team_matches[away_col].notnull().mean()
        dataset.loc[(dataset["home_team"] == home_team), home_col] = home_team_matches[home_col].fillna(value = home_col_new_value)
        dataset.loc[(dataset["away_team"] == away_team), away_col] = away_team_matches[away_col].fillna(value = away_col_new_value)

In [90]:
dataset.head()

,Division,home_team,away_team,half_time_home_goals,half_time_away_goals,Referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,...,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef,result
0,0,152.0,426.0,0.0,0.0,-1,0.180723,0.161616,0.180723,0.161616,...,0.180723,0.161616,0.180723,0.161616,0.180723,0.161616,3.627690,3.577721,2.198600,0
1,0,216.0,341.0,0.0,1.0,-1,0.830000,0.253731,0.830000,0.253731,...,0.830000,0.253731,0.830000,0.253731,0.830000,0.253731,1.608321,4.251999,6.533805,0
2,0,223.0,119.0,2.0,0.0,-1,0.489796,0.000000,0.489796,0.000000,...,0.489796,0.000000,0.489796,0.000000,0.489796,0.000000,2.166811,3.486596,3.821467,0
3,0,68.0,137.0,0.0,1.0,-1,0.151515,0.238806,0.151515,0.238806,...,0.151515,0.238806,0.151515,0.238806,0.151515,0.238806,2.259244,3.592401,3.460103,1
4,1,425.0,225.0,1.0,0.0,-1,13.000000,11.000000,5.000000,7.000000,...,4.000000,10.000000,3.000000,4.000000,1.000000,0.000000,2.424278,3.414191,3.282876,0

In [91]:
dataset.columns

Index(['Division', 'home_team', 'away_team', 'half_time_home_goals',
       'half_time_away_goals', 'Referee', 'home_shots', 'away_shots',
       'home_shots_on_target', 'away_shots_on_target', 'home_fouls',
       'away_fouls', 'home_corners', 'away_corners', 'home_yellow_cards',
       'away_yellow_cards', 'home_red_cards', 'away_red_cards', 'home_coef',
       'draw_coef', 'away_coef', 'result'],
      dtype='object')

In [92]:
dataset.isnull().sum()

Division                0
home_team               0
away_team               0
half_time_home_goals    0
half_time_away_goals    0
Referee                 0
home_shots              0
away_shots              0
home_shots_on_target    0
away_shots_on_target    0
home_fouls              0
away_fouls              0
home_corners            0
away_corners            0
home_yellow_cards       0
away_yellow_cards       0
home_red_cards          0
away_red_cards          0
home_coef               0
draw_coef               0
away_coef               0
result                  0
dtype: int64

In [104]:
dataset.head(10)

,Division,home_team,away_team,half_time_home_goals,half_time_away_goals,Referee,home_shots,away_shots,home_shots_on_target,away_shots_on_target,...,home_corners,away_corners,home_yellow_cards,away_yellow_cards,home_red_cards,away_red_cards,home_coef,draw_coef,away_coef,result
0,0,152.0,426.0,0.0,0.0,-1,0.180723,0.161616,0.180723,0.161616,...,0.180723,0.161616,0.180723,0.161616,0.180723,0.161616,3.627690,3.577721,2.198600,0
1,0,216.0,341.0,0.0,1.0,-1,0.830000,0.253731,0.830000,0.253731,...,0.830000,0.253731,0.830000,0.253731,0.830000,0.253731,1.608321,4.251999,6.533805,0
2,0,223.0,119.0,2.0,0.0,-1,0.489796,0.000000,0.489796,0.000000,...,0.489796,0.000000,0.489796,0.000000,0.489796,0.000000,2.166811,3.486596,3.821467,0
3,0,68.0,137.0,0.0,1.0,-1,0.151515,0.238806,0.151515,0.238806,...,0.151515,0.238806,0.151515,0.238806,0.151515,0.238806,2.259244,3.592401,3.460103,1
4,1,425.0,225.0,1.0,0.0,-1,13.000000,11.000000,5.000000,7.000000,...,4.000000,10.000000,3.000000,4.000000,1.000000,0.000000,2.424278,3.414191,3.282876,0
5,1,393.0,300.0,0.0,0.0,-1,6.000000,6.000000,1.000000,2.000000,...,6.000000,8.000000,1.000000,0.000000,0.000000,0.000000,2.787163,3.375001,2.817568,0
6,1,239.0,140.0,0.0,0.0,-1,16.000000,4.000000,8.000000,1.000000,...,6.000000,1.000000,0.000000,2.000000,0.000000,0.000000,2.080239,3.582070,3.998117,0
7,1,211.0,424.0,1.0,0.0,-1,18.000000,5.000000,7.000000,3.000000,...,6.000000,6.000000,2.000000,1.000000,0.000000,1.000000,2.099892,3.449822,4.099789,1
8,1,99.0,5.0,0.0,0.0,-1,9.000000,5.000000,5.000000,2.000000,...,6.000000,4.000000,0.000000,1.000000,0.000000,0.000000,1.312957,5.807312,13.129574,1
9,0,303.0,382.0,1.0,0.0,-1,0.000000,0.468750,0.000000,0.468750,...,0.000000,0.468750,0.000000,0.468750,0.000000,0.468750,1.528475,4.476952,7.553624,1

#### Save processed data

In [94]:
dataset.to_csv("processed_train.csv", index = False)

## Train, Test and Save Model using Naive Bayes and SVM

In [99]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
import pickle

X_train, X_test, y_train, y_test = train_test_split(dataset.drop(columns=["result"]), dataset["result"], test_size=0.3,random_state=109)

### Naive Bayes

In [100]:
gnb = GaussianNB()

In [101]:
gnb.fit(X_train, y_train)

GaussianNB()

In [102]:
#Predict the response for test dataset
y_pred = gnb.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5550925154192365

In [ ]:
filename = 'modelFile'
pickle.dump(model, open(filename, 'wb'))

#### SVM (not trained because training time is too long)

In [20]:
#Create a svm Classifier
clf = svm.SVC(kernel='poly', degree=2, gamma=1, verbose=True) # Linear Kernel

In [ ]:
#Train the model using the training sets
clf.fit(X_train, y_train)

[LibSVM]

In [ ]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))